### ISSUE TITLE
Logs displaying in severity order instead of chronological

### ISSUE THREAD

**Issue by manwaring** [iopipe/iopipe-js-logger#13]
I love this new logger plugin - thanks for making something so easy to use!

One issue I've found is that the logs aren't displaying in the UI according to timestamp when I use different log levels (console.debug, console.error, etc.).  It looks like the logs are showing up in severity order first and then chronologically within each severity.  I was expecting that all logs would display chronologically across all levels - the way it is now makes it hard to understand what was happening during the invocation.

<img width="888" alt="screen shot 2018-08-13 at 9 44 02 am" src="https://user-images.githubusercontent.com/2955468/44035621-e80476ae-9edd-11e8-93b8-355c8bf99da3.png">

**Comment by pselle** [comment]
@manwaring Wanted to let you know that we've updated this and it should be fixed! Appreciate the report.
