### ISSUE TITLE
Warn if working with incompatible version of core

### ISSUE THREAD

**Issue by kolanos** [iopipe/iopipe-js-logger#14]
Plugin should provide a warning if it detects it is being used with a version of `iopipe-js-core` less than `v1.13.0`. Older versions of `iopipe-js-core` don't include the file upload functionality and as such are incompatible.

**Comment by pselle** [comment]
Isn't this solved by virtue of dependency management? https://github.com/iopipe/iopipe-js-logger/blob/master/package.json#L51
